[package]
name = "truescad"
version = "0.7.2"
authors = ["Henning Meyer <tutmann@gmail.com>"]

[dependencies]
dirs = "1.0"
sourceview = "^0"
gdk = "^0"
cairo-rs = "^0"
nalgebra = "0.16"
alga = "0.7"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
num-traits = "0.2"
tessellation = "0.7"
truescad_luascad = { path = "luascad" }
kiss3ddeps = { path = "kiss3ddeps" }
stl_io = "0.3"
kiss3d = "0.13"

[dev-dependencies]
bencher = "0.1.*"

[patch.crates-io]
gtk = { path = "gtk" }

[features]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]

[dependencies.gtk]
version = "0.5"
features = ["v3_16"]

# [profile.release]
# lto = true

[[bench]]
name = "render"
harness = false
